# Generated by Django 2.1.7 on 2019-02-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='record',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='record',
            name='description',
        ),
        migrations.RemoveField(
            model_name='record',
            name='subject',
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(default='Other', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='entity',
            field=models.CharField(blank=True, max_length=64, verbose_name='the other entity in the tradeoff'),
        ),
        migrations.AddField(
            model_name='record',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
