# Generated by Django 2.1.7 on 2019-02-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190226_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='recordType',
            field=models.ForeignKey(default='Expense', on_delete=django.db.models.deletion.CASCADE, to='webapp.RecordType'),
            preserve_default=False,
        ),
    ]
